# 
# This source code is copyrighted by Montimage. It is released under MIT license.
# It is part of the French National Research Agency (ANR) MOSAICO project, under grant No ANR-19-CE25-0012.
#


TCP_OR_UDP_ATTRIBUTES='"udp.src_port","udp.dest_port","udp.len"'
if [[ "$TYPE" == "iperf3" ]]; then
	TCP_OR_UDP_ATTRIBUTES='"tcp.src_port","tcp.dest_port","tcp.payload_len"'
fi
# attributes to collect. They must be in syntax: proto.att_name as being defined by MMT
ATTRIBUTES=$(cat <<EOF
	"meta.packet_len",
	"ip.src", 
	"ip.dst", 
	"ip.proto_tos", 
	"ip.ecn",
	"ip.identification", 
	$TCP_OR_UDP_ATTRIBUTES,
	"quic_ietf.header_form",
	"quic_ietf.spin_bit",
	"quic_ietf.rtt",
	"int.hop_queue_ids",
	"int.hop_latencies", 
	"int.hop_queue_occups",
	"int.hop_ingress_times", 
	"int.hop_egress_times",
	"int.hop_l4s_mark", 
	"int.hop_l4s_drop",
	"int.hop_tx_utilizes"
EOF
)
# NOTE: override "hop_tx_utilizes" to carry "int.mark_probability"


# the "name" of the attributes above to show as CSV header.
# They can be any string as you want
ATTRIBUTES_HEADERS=$(
	# I temporarily use hop_tx_utilizes to carry info about mark_probability
	echo "$ATTRIBUTES" | sed --expression="s/int.hop_tx_utilizes/int.mark_probability/"
)
	
	
function combine-mmt-csv-files(){
	OUTPUT=$1
	HEADER=$(echo "report-id,probe-id,source,timestamp,report-name,meta.packet_index,$ATTRIBUTES_HEADERS" | tr -d '"' | tr -d "\n" | tr -d "[:blank:]" )
	echo "$HEADER" > "$OUTPUT"

	for f in $(find . -name '1*.csv'); do
		echo " $f"
		#            only event reports
		cat "$f" | grep "^1000," >> "$OUTPUT"
		rm  -- "$f"
	done
}

function generate-monitor-config(){
	cat <<EOF
# Generated by script on $(date)
event-report int {
	enable = true
	# only capture UDP packet
	event  =  "meta.packet_index"
	delta-cond = {}
	attributes = { $ATTRIBUTES }
	output-channel = {file}
}
EOF
}

# run directly
ACTION="$1"
if [[ "$ACTION" == "combine-mmt-csv-files" ]]; then
	combine-mmt-csv-files data.csv
fi
