#!/bin/bash

SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
# load predefined environment variables
MMT_CONFIG_FILE="$SCRIPT_PATH/mmt-probe.conf"


# attributes to collect. They must be in syntax: proto.att_name as being defined by MMT
MMT_ATTRIBUTES=$(cat <<EOF
	"meta.packet_len",
	"ip.src", 
	"ip.dst", 
	"ip.proto_tos", 
	"ip.ecn",
	"ip.identification", 
	"udp.src_port","udp.dest_port","udp.len",
	"tcp.src_port","tcp.dest_port","tcp.payload_len","tcp.seq_nb","tcp.ack_nb","tcp.tsval","tcp.tsecr",
	"quic_ietf.header_form",
	"quic_ietf.spin_bit",
	"quic_ietf.rtt",
	"int.hop_queue_ids",
	"int.hop_latencies", 
	"int.hop_queue_occups",
	"int.hop_ingress_times", 
	"int.hop_egress_times",
	"int.hop_l4s_mark", 
	"int.hop_l4s_drop",
	"int.hop_tx_utilizes"
EOF
)
# NOTE: override "hop_tx_utilizes" to carry "int.mark_probability"


# the "name" of the attributes above to show as CSV header.
# They can be any string as you want
MMT_ATTRIBUTES_HEADERS=$(
	# I temporarily use hop_tx_utilizes to carry info about mark_probability
	echo "$MMT_ATTRIBUTES" | sed --expression="s/int.hop_tx_utilizes/int.mark_probability/"
)
	
	
function combine-mmt-csv-files(){
	OUTPUT=$1
	HEADER=$(echo "report-id,probe-id,source,timestamp,report-name,meta.packet_index,$MMT_ATTRIBUTES_HEADERS" | tr -d '"' | tr -d "\n" | tr -d "[:blank:]" )
	echo "$HEADER" > "$OUTPUT"

	for f in $(find . -name '1*.csv'); do
		echo " $f"
		#            only event reports
		cat "$f" | grep "^1000," >> "$OUTPUT"
		rm  -- "$f"
	done
}

function generate-monitor-config(){
	cat <<EOF
# Generated by script on $(date)
event-report int {
	enable = true
	# only capture UDP packet
	event  =  "meta.packet_index"
	delta-cond = {}
	attributes = { $MMT_ATTRIBUTES }
	output-channel = {file}
}
EOF
}


function start-monitoring(){
	cd -- "$LOG"
	
	# start pcap dumping
	log "start pcap dump"
	FILTER="tcp or udp"
	
	# store only first 128 bytes that should be nought for ETH/IP/UDP/QUIC-header
	tcpdump --snapshot-length=128 -i enp0s8  -w enp0s8-data.pcap "$FILTER" &
	tcpdump --snapshot-length=128 -i enp0s9  -w enp0s9-data.pcap "$FILTER" &
	# store only the first 176 bytes that should be enougth for ETH/IP/UDP/INT/QUIC-header
	tcpdump --snapshot-length=176 -i enp0s10 -w enp0s10-int.pcap "$FILTER" &
	sleep 1

	# generate config file
	cp -- "$MMT_CONFIG_FILE" ./mmt-probe.conf
	generate-monitor-config >> mmt-probe.conf

	log "start mmt-probe"
	(mmt-probe -c ./mmt-probe.conf -i enp0s10 > mmt-probe.log 2>&1) &
	sleep 2
}



function stop-monitoring(){
	cd -- "$LOG"

	log "stop tcpdump and mmt-probe"
	killall --signal SIGINT tcpdump
	killall --signal SIGINT mmt-probe
	
	sleep 2

	tar -czf pcap.tar.gz enp0s8-data.pcap enp0s9-data.pcap enp0s10-int.pcap
	# test to run mmt offline
	#mmt-probe -t enp0s10-int.pcap
	
	rm enp0s8-data.pcap enp0s9-data.pcap enp0s10-int.pcap

	log "processing MMT files ..."
	combine-mmt-csv-files data.csv
	tar -czf data.csv.tar.gz data.csv
	#plot graph
	python3 "$SCRIPT_PATH/monitoring-mmt-tcpdump.plot.py" data.csv
	rm data.csv
}


# run directly
ACTION="$1"
if [[ "$ACTION" == "combine-mmt-csv-files" ]]; then
	combine-mmt-csv-files data.csv
fi