for ROUND in 1 2 3 4 5
do
   ID="round-$ROUND"

   # remove picoquic logs
   find $ID -name qlog -exec rm -rf '{}' \;
   # remove graph whose size > 300K. We can be regenerated by ../monitoring-mmt-tcpdump.plot.sh
   find $ID -type f -name "*.png" -size "+300K" -delete
   # remove pcap files
   find $ID -type f -name "pcap.tar.gz" -delete
   # delete conf of MMT
   find $ID -type f -name "mmt-probe.conf" -delete
done
